import { Dock, DockIcon, DockItem, DockLabel } from '@/components/ui/dock'
import { BriefcaseBusiness, FileCode, GraduationCap, HomeIcon } from 'lucide-react'
import type { Metadata } from 'next'
import { Libre_Bodoni, Signika_Negative } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const signikaNegative = Signika_Negative({
  variable: '--font-signika-negative',
  subsets: ['latin']
})

const libreBodoni = Libre_Bodoni({
  variable: '--font-libre-bodoni',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const apps = [
    {
      title: 'Home',
      icon: <HomeIcon className='h-full w-full text-neutral-600 dark:text-neutral-300' />,
      href: '/'
    },
    {
      title: 'Education',
      icon: <GraduationCap className='h-full w-full text-neutral-600 dark:text-neutral-300' />,
      href: '/education'
    },
    {
      title: 'Case Studies',
      icon: <BriefcaseBusiness className='h-full w-full text-neutral-600 dark:text-neutral-300' />,
      href: '/case-studies'
    },
    {
      title: 'Code Showcase',
      icon: <FileCode className='h-full w-full text-neutral-600 dark:text-neutral-300' />,
      href: '/code-showcase'
    }
  ]

  return (
    <html lang='en'>
      <body className={`${signikaNegative.variable} ${libreBodoni.variable} antialiased relative min-h-screen`}>
        {children}
        <div className='fixed bottom-2 left-1/2 w-full -translate-x-1/2 z-10'>
          <Dock className='items-end pb-3'>
            {apps.map((app, idx) => (
              <Link href={app.href} key={idx}>
                <DockItem className='aspect-square rounded-full bg-gray-200 dark:bg-neutral-800 cursor-pointer'>
                  <DockLabel>{app.title}</DockLabel>
                  <DockIcon>{app.icon}</DockIcon>
                </DockItem>
              </Link>
            ))}
          </Dock>
        </div>
      </body>
    </html>
  )
}
