import { Dock, DockIcon, DockItem, DockLabel } from '@/components/ui/dock'
import { Braces, BriefcaseBusiness, GraduationCap, HomeIcon } from 'lucide-react'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const data = [
    {
      title: 'Home',
      icon: <HomeIcon className='h-full w-full text-neutral-600 dark:text-neutral-300' />,
      href: '/'
    },
    {
      title: 'Education',
      icon: <GraduationCap className='h-full w-full text-neutral-600 dark:text-neutral-300' />,
      href: '/education'
    },
    {
      title: 'Case Studies',
      icon: <BriefcaseBusiness className='h-full w-full text-neutral-600 dark:text-neutral-300' />,
      href: '/case-studies'
    },
    {
      title: 'Components Library',
      icon: <Braces className='h-full w-full text-neutral-600 dark:text-neutral-300' />,
      href: '/components-library'
    }
  ]

  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}>
        {children}
        <div className='fixed bottom-2 left-1/2 w-full -translate-x-1/2 z-10'>
          <Dock className='items-end pb-3'>
            {data.map((item, idx) => (
              <Link href={item.href} key={idx}>
                <DockItem className='aspect-square rounded-full bg-gray-200 dark:bg-neutral-800 cursor-pointer'>
                  <DockLabel>{item.title}</DockLabel>
                  <DockIcon>{item.icon}</DockIcon>
                </DockItem>
              </Link>
            ))}
          </Dock>
        </div>
      </body>
    </html>
  )
}
